#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

adduser mailcatcher --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
mkdir /opt
cd /opt || exit
git clone https://github.com/maildev/maildev ./mailcatcher -b v2.0.5
cd /usr/local/hestia/plugins/mailcatcher || exit
rsync -r ./src/ /opt/mailcatcher
chown -R mailcatcher:mailcatcher /opt/mailcatcher
runuser -s /bin/bash -l mailcatcher -c "cd /opt/mailcatcher && source /opt/nvm/nvm.sh && nvm use v16 && npm install"


# Swap out sendmail for mailcatcher
mv /usr/sbin/sendmail /usr/sbin/sendmail.pre-mailcatcher-sav
if [ ! -L /usr/sbin/sendmail.pre-mailcatcher-sav ] ; then
    mv /usr/sbin/sendmail /usr/sbin/sendmail.pre-mailcatcher-sav
fi
ln -s /opt/mailcatcher/bin/cli.js /usr/sbin/sendmail
ln -s /usr/sbin/sendmail /usr/local/bin/sendmail

/usr/local/hestia/bin/v-add-user-notification admin "MailCatcher" "<span style=\"color:white;\"><i class=\"fas fa-envelope\"></i></span> MailCatcher plugin has finished installing."
