#!/bin/bash
runuser -l maildev -c "cd /opt/maildev && source /opt/nvm/nvm.sh && pm2 delete maildev ; pm2 save --force"
rm -rf /opt/maildev
rm -rf /opt/catchmail-node
deluser maildev
rm -rf /home/maildev
php -r "include('/usr/local/hestia/web/pluginable.php');global \$hcpp;\$hcpp->delete_port('maildev_port');"
